# WebShop評価用 Llama 3.2 3B Instruct設定ファイル

# ABCIジョブ設定
job:
  name: webshop_o4-mini
  walltime: "1:00:00"  
  project: gcb50389
  queue: rt_HC
  output_dir: logs/abci

# モデル設定
model:
  name: "o4-mini"
  temperature: 0.1
  max_new_tokens: 512
  top_p: 0.9
  top_k: 50
  
  # HuggingFace固有設定
  device: "auto"
  load_in_8bit: false
  load_in_4bit: true  # 4bit量子化を使用してメモリ節約
  trust_remote_code: false
  torch_dtype: "auto"

# エージェント設定
agent:
  type: "openai"
  max_steps: 5  # テスト用。全体実行時には大きくする.
  verbose: true  # actionとobservationの詳細ログ出力

# 評価設定
evaluation:
  # タスク範囲: submit_abci_jobs.shのTOTAL_TASKSで制御されるため、
  # ここでは最大タスク数を指定（バッチジョブで適切に分割される）
  task_start_idx: 0
  task_end_idx: 10  # 8タスク以上に設定
  results_dir: "results/abci"

# バッチジョブ設定
batch:
  job_id: null
  
# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 